{
 "title": "Simplified Payment Gateway - Modules",
 "tags": [
  "application",
  "modules"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Transaction Module", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Transactions - RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "rate(simplified_payment_gateway_http_requests_count{request_path=~\"/api/v1/transactions.*\"}[1m])",
     "legendFormat": "{{request_path}} ({{request_status}})"
    }
   ]
  },
  {
   "title": "Transactions - Duration (P95)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, rate(simplified_payment_gateway_http_requests_bucket{request_path=~\"/api/v1/transactions.*\"}[5m]))",
     "legendFormat": "P95 {{request_path}}"
    }
   ]
  },
  { "title": "Account Module", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Accounts - RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "rate(simplified_payment_gateway_http_requests_count{request_path=~\"/api/v1/accounts.*\"}[1m])",
     "legendFormat": "{{request_path}} ({{request_status}})"
    }
   ]
  },
  {
   "title": "Accounts - Duration (P95)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, rate(simplified_payment_gateway_http_requests_bucket{request_path=~\"/api/v1/accounts.*\"}[5m]))",
     "legendFormat": "P95 {{request_path}}"
    }
   ]
  }
 ]
}